import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useRef } from 'react';
import Tilt from 'react-tilt'

export default function Home() {
  const cursorDiv = useRef(null)
  const tiltImage = () => {
    return `https://picsum.photos/200/200`
  }
  const keyStr =
  'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='
  const triplet = (e1, e2, e3) =>
  keyStr.charAt(e1 >> 2) +
  keyStr.charAt(((e1 & 3) << 4) | (e2 >> 4)) +
  keyStr.charAt(((e2 & 15) << 2) | (e3 >> 6)) +
  keyStr.charAt(e3 & 63)

  const rgbDataURL = (r, g, b) =>
  `data:image/gif;base64,R0lGODlhAQABAPAA${
    triplet(0, r, g) + triplet(b, 255, 255)
  }/yH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==`
  let cursorTimeout = null;
  useEffect(() => {
    if (typeof window !== 'undefined') {
      document.addEventListener('click', function(e) {
        e.stopImmediatePropagation()

        if(e.target.tagName === 'A' || e.target.tagName === 'BUTTON' || e.target.tagName === 'INPUT') {
          clearTimeout(cursorTimeout)

          cursorDiv.current.classList.add('--shadow')
          cursorDiv.current.style.top = `${e.pageY}px`
          cursorDiv.current.style.left = `${e.pageX}px`
  
          cursorTimeout = setTimeout(() => {
            cursorDiv.current.classList.remove('--shadow')
          }, 200);
        }
      }, true)
    }
  })

    return (
      <div>
        <Head>
          <title>Animations</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <section className='section'>
            <h1>Images (lazyloading placeholder & tilt)</h1>
            <Tilt className="Tilt" options={{ max: 10, reverse: true }} style={{ height: 200, width: 200 }} >
              <div className="Tilt-inner"><Image loader={tiltImage} placeholder="blur" blurDataURL={rgbDataURL(2, 129, 210)} src="false" alt='picsum' width={200} height={200} /></div>
            </Tilt>
          </section>
          <section className='section'>
            <h1>Form</h1>
            <form>
              <input type="text" className='input input--text --outline-normal' placeholder='input text'/>
              <input type="text" className='input input--text --outline-shadow' placeholder='input text'/>
              <div className="input input--radio">
                <label htmlFor="radio1">Click me</label>
                <input type="radio" id="radio1" name="radiogroup1" />
                <span></span>
              </div>

              <div className="input input--toggle">
                <label htmlFor="toggle1">Toggle me</label>
                <input type="checkbox" id="toggle1" />
                <span></span>
              </div>
            </form>
          </section>
          <section className='section'>
            <h1>Buttons</h1>
            <button className='btn'>button</button>
            <button className='btn btn--loading'>
            <svg class="loader" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle style={{ 'opacity': 0.25 }} cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path style={{ 'opacity': 0.75 }} fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
             button</button>
          </section>
          <section className='section'>
            <h1>Links</h1>
            <a href="#" className='link --animated'>Dit is een link</a><br></br>
          </section>
          <section className='section'>
            <h1>Icons</h1>
            <svg className='icon icon--shaking' xmlns="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/1999/xlink" version="1.1" viewBox="0 0 512 512" enable-background="new 0 0 512 512" width={20}>
              <g>
                <g>
                  <path d="m485.7,198.5c-10.7-13.4-25.3-20.8-41.1-20.8h-36.1c-3.4-92.6-70.5-166.7-152.5-166.7-82,0-149.1,74.1-152.5,166.7h-36.1c-15.8,0-30.4,7.4-41.1,20.8-13.5,16.8-18.4,40.2-13.3,62.7l43.3,190.8c6.5,28.8 28.9,49 54.4,49h290.5c25.5,0 47.9-20.1 54.4-49l43.4-190.8c5.1-22.5 0.2-45.9-13.3-62.7zm-229.7-146.7c59.6-1.42109e-14 108.4,55.8 111.6,125.9h-223.2c3.2-70 52-125.9 111.6-125.9zm203.2,200.3l-43.3,190.9c-2.2,9.8-8.5,17.2-14.6,17.2h-290.6c-6.1,0-12.4-7.4-14.6-17.2l-43.3-190.9c-2.3-10.1-3.7-33.6 14.6-33.6h377.2c19.7,0 16.9,23.5 14.6,33.6z"/>
                  <path d="m154.7,259.1c-11.3,0-20.4,9.1-20.4,20.4v127.5c0,11.3 9.1,20.4 20.4,20.4 11.3,0 20.4-9.1 20.4-20.4v-127.5c0.1-11.2-9.1-20.4-20.4-20.4z"/>
                  <path d="m253.6,259.1c-11.3,0-20.4,9.1-20.4,20.4v127.5c0,11.3 9.1,20.4 20.4,20.4 11.3,0 20.4-9.1 20.4-20.4v-127.5c0-11.2-9.2-20.4-20.4-20.4z"/>
                  <path d="m352.4,259.1c-11.3,0-20.4,9.1-20.4,20.4v127.5c0,11.3 9.1,20.4 20.4,20.4 11.3,0 20.4-9.1 20.4-20.4v-127.5c5.68434e-14-11.2-9.1-20.4-20.4-20.4z"/>
                </g>
              </g>
            </svg>
          </section>
          <section className='section'>
            <h1>Progressbar</h1>
            <div className='progressbar'>
              <div className="progressbar__indicator"><div></div></div>
            </div>
          </section>
          <div className='cursor' ref={cursorDiv}></div>
        </main>
      </div>
    )
}